#pragma once

#define IMGUI_ENABLE_FREETYPE

#define CHERRY_VULKAN
// #define CHERRY_STATIC
// #define CHERRY_MULTIAPP
// #define CHERRY_PACKAGE
#define CHERRY_DEBUG

// #define CHERRY_ENABLE_SHADERS
// #define CHERRY_ENABLE_NET
// #define CHERRY_ENABLE_AUDIO
// #define CHERRY_ENABLE_KIT
#define CHERRY_ENABLE_SCRIPTING
// #define CHERRY_ENABLE_LINUXDRM
// #define CHERRY_ENABLE_NODES
// #define CHERRY_ENABLE_WORKSPACESAVES