name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies and Configure Build (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake make g++
        sudo apt-get install -y libvulkan-dev xorg-dev
        sudo apt-get install -y libfmt-dev libsdl2-dev libsdl2-image-dev

        # Initialize and update submodules
        git submodule update --init --recursive

        # Configure and build
        cd "examples/hello"
        sudo bash build.sh

    - name: Install CMake and Vulkan SDK (windows-latest)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install vulkan-sdk

        # Initialize and update submodules
        git submodule update --init --recursive

        # Configure and build
        cd "examples/hello"
        ./build.bat
